### PR TITLE
RoboSub 2024

### PR DESCRIPTION
**Pull request by maxwellmlin**
See parent branch `comp-2024` for original competition code. This `comp-2024-refactor` branch contains the refactored code to be merged into `master`.

- [x] Onboard packages
  - [x] cv @nathanaelren @ChuChuCodes0414 
  - [x] sonar @Will-Denton 
  - [x] data_pub @mbryant2025 @PatrickZheng0 
  - [x] offboard_comms @mbryant2025 @PatrickZheng0 
  - [x] controls @maxwellmlin 
  - [x] system_utils @maxwellmlin 
  - [x] sensor_fusion @maxwellmlin 
  - [x] execute @maxwellmlin 
  - [x] task_planning @viethungle-vt1401 @maxwellmlin 
- [x] Everything outside onboard @maxwellmlin

### CODE REVIEW

**Review by nathanaelren — APPROVED** [review]
lgtm

**Review by ChuChuCodes0414 — DISMISSED** [review]
LGTM (i have no clue what this code does)

**Review by nathanaelren — APPROVED** [review]
excellent

**Comment by maxwellmlin** [comment]
@vedarshshah https://github.com/DukeRobotics/robosub-ros/actions/runs/10648366606/job/29517336960?pr=555

Actions seems to be failing because of `record_bag`. Can you fix?

**Review by PatrickZheng0 — APPROVED** [review]

**Review by viethungle-vt1401 — APPROVED** [review]
Let's Gamble, Try Merging

**Pull request merged**
