### PR TITLE
Github Super-Linter

### PR DESCRIPTION
**Pull request by muthuArivoli**
Lints the codebase using the following linters:

Bash: shellcheck, also checks for executable
Python: flake8

I have disabled lua linting because that threw ~600 errors for bad code during linting.

I decided to not lint markdown, since it seems to be annoying changes that don't actually make a difference on the rendered output. I decided not to lint the dockerfiles since I was literally ignoring all the errors that the linter threw. It asked to do things like pin package versions, which is good practice for industry, but really doesn't matter for us. I decided not to do xml or yaml since those seemed to not really do anything. Also, this way, we are linting only the code in the repo. 

Will add luachecks once the lua code is rewritten. Will add clang-tidy for c++ once the super linter supports it.

### CODE REVIEW

**Comment by muthuArivoli** [comment]
Alright, could everyone review this and also test this locally to make sure this PR doesn't break any of their stuff. Put a check in the box when you've tested it and are satisfied with the linting.

- [ ] Simulation: @puzzler7 
- [ ] Controls: @ShaanGondalia @rabinowitz 
- [ ] Motion Planning: @echang264 @davidAmiron

**Review by davidAmiron — APPROVED** [review]
Looks good

**Comment by ShaanGondalia** [comment]
LGTM

**Comment by echang264** [comment]
LGTM

**Review by rabinowitz — APPROVED** [review]
LGTM, I'll take Shaan's word for it that controls works. Make sure you Squash and Merge.

**Pull request merged**
