### PR TITLE
Torpedo arduino

### PR DESCRIPTION
**Pull request by mbryant2025**
Introduces servo control functionality. Servo actuation is controlled by a standalone Arduino, which is activated by a service.

Additionally, with the addition of another Arduino, serial publishing was abstracted into a SerialPublisher base class to be inherited from.

Also included are temperature and humidity functionality from the same Arduino as the servo. Temperature and humidity are also shown in the status panel, and the corresponding configuration files have been updated.

### CODE REVIEW

**Review by PatrickZheng0 — APPROVED** [review]
foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx - line 85 - context.onRender = (renderState: Immutable<RenderState>, done): is context.onRender a ROS thing or where does it come from, where does the frames come from in terms of the code too? Is it a GUI we made?

onboard/catkin_ws/src/data_pub/scripts/serial_publisher.py - line 51 - while ((time.time() - start) < tout) and (b'\r\n' not in buff): what is the b-string in this context and why is it used? what's the purpose of '\r\n'?

**Review by joycehuu — APPROVED** [review]

**Review by cbrantley318 — APPROVED** [review]

**Review by MiaKaarls — APPROVED** [review]

**Review by maanav13579 — APPROVED** [review]

**Comment by vedarshshah** [comment]
> foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx - line 85 - context.onRender = (renderState: Immutable, done): is context.onRender a ROS thing or where does it come from, where does the frames come from in terms of the code too? Is it a GUI we made?
> 
> onboard/catkin_ws/src/data_pub/scripts/serial_publisher.py - line 51 - while ((time.time() - start) < tout) and (b'\r\n' not in buff): what is the b-string in this context and why is it used? what's the purpose of '\r\n'?

@PatrickZheng0 System Status Panel is a custom panel we made for [Foxglove](https://foxglove.dev) – a platform for visualizing ROS data. The panel provides the status of various system parameters, such as CPU & RAM usage, voltage, and (added in this PR) humidity and temperature. Foxglove does most of the heavy lifting of obtaining and parsing the raw data from ROS; it provides this data in a convenient format to panels through `context.onRender` and `renderState`. `context.onRender` is part of [Foxglove's PanelExtensionContext](https://docs.foxglove.dev/docs/visualization/extensions/api/panel/). It is called by Foxglove whenever the panel needs to update, such as when a new message was published to a topic that the panel is subscribed to. As part of `context.onRender`, Foxglove provides `renderState`, which contains the information the panel needs to update itself. `renderState` includes frames, which contain the new subscribed messages. 

A few facts to answer your second question:
- "b-strings" in python denotes a sequence of `bytes` – a distinct type in Python. They are different from regular strings (with no prefix), of type `str`, which are meant to be human-readable. This [StackOverflow post](https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal) provides more information about the difference between the two.
- The character `\r` denotes carriage return and `\n` denotes line feed (character codes 13 and 10, respectively, see [ASCII table](https://www.asciitable.com)). When Arduino prints a line to serial, it terminates the line with the combination of these two characters `\r\n`. 
- The [documentation for the `Serial.read` function](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.read) indicates that it has one parameter to specify the number of bytes to read. It returns the byte(s) it read; the return type is `bytes`. 

Putting this together, let's understand how the `readline_nonblocking` function works. It first records the `start` timestamp and initializes `buff` to be a sequence of `bytes`, since the values read from serial are `bytes`. In the loop, it tries to read one byte from serial. If if successfully read a byte, the byte is appended to `buff`. If it is unable to read a byte, it loops back and tries again. The loop will exit when either it has finished reading a complete line, which it checks for by checking if the line separator `\r\n` is in `buff`, or when the total time spent trying to read the line has exceeded `tout`, which it checks for by checking the time elapsed between the current timestamp and the `start` timestamp. At the end, it converts `buff` to type `str` by decoding it with UTF-8 encoding and returns the converted string.

For future PR reviews, if you have a comment related to specific line(s) of code, go to "Files Changed", hover over the line you have a comment about, click the blue plus icon next to it, and write your comment in the box that opened up. GitHub will automatically include that line (as well as a few before it) in the comment using proper code formatting. This way, it's easier to read the code you have a comment about and reference it within the file.

**Comment by PatrickZheng0** [comment]
> > foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx - line 85 - context.onRender = (renderState: Immutable, done): is context.onRender a ROS thing or where does it come from, where does the frames come from in terms of the code too? Is it a GUI we made?
> > onboard/catkin_ws/src/data_pub/scripts/serial_publisher.py - line 51 - while ((time.time() - start) < tout) and (b'\r\n' not in buff): what is the b-string in this context and why is it used? what's the purpose of '\r\n'?
> 
> @PatrickZheng0 System Status Panel is a custom panel we made for [Foxglove](https://foxglove.dev) – a platform for visualizing ROS data. The panel provides the status of various system parameters, such as CPU & RAM usage, voltage, and (added in this PR) humidity and temperature. Foxglove does most of the heavy lifting of obtaining and parsing the raw data from ROS; it provides this data in a convenient format to panels through `context.onRender` and `renderState`. `context.onRender` is part of [Foxglove's PanelExtensionContext](https://docs.foxglove.dev/docs/visualization/extensions/api/panel/). It is called by Foxglove whenever the panel needs to update, such as when a new message was published to a topic that the panel is subscribed to. As part of `context.onRender`, Foxglove provides `renderState`, which contains the information the panel needs to update itself. `renderState` includes frames, which contain the new subscribed messages.
> 
> A few facts to answer your second question:
> 
> * "b-strings" in python denotes a sequence of `bytes` – a distinct type in Python. They are different from regular strings (with no prefix), of type `str`, which are meant to be human-readable. This [StackOverflow post](https://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal) provides more information about the difference between the two.
> * The character `\r` denotes carriage return and `\n` denotes line feed (character codes 13 and 10, respectively, see [ASCII table](https://www.asciitable.com)). When Arduino prints a line to serial, it terminates the line with the combination of these two characters `\r\n`.
> * The [documentation for the `Serial.read` function](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.read) indicates that it has one parameter to specify the number of bytes to read. It returns the byte(s) it read; the return type is `bytes`.
> 
> Putting this together, let's understand how the `readline_nonblocking` function works. It first records the `start` timestamp and initializes `buff` to be a sequence of `bytes`, since the values read from serial are `bytes`. In the loop, it tries to read one byte from serial. If if successfully read a byte, the byte is appended to `buff`. If it is unable to read a byte, it loops back and tries again. The loop will exit when either it has finished reading a complete line, which it checks for by checking if the line separator `\r\n` is in `buff`, or when the total time spent trying to read the line has exceeded `tout`, which it checks for by checking the time elapsed between the current timestamp and the `start` timestamp. At the end, it converts `buff` to type `str` by decoding it with UTF-8 encoding and returns the converted string.
> 
> For future PR reviews, if you have a comment related to specific line(s) of code, go to "Files Changed", hover over the line you have a comment about, click the blue plus icon next to it, and write your comment in the box that opened up. GitHub will automatically include that line (as well as a few before it) in the comment using proper code formatting. This way, it's easier to read the code you have a comment about and reference it within the file.

I see, this all makes sense. Thank you!

**Comment by maxwellmlin** [comment]
Included in https://github.com/DukeRobotics/robosub-ros/pull/555.

**Pull request closed without merging**
